!fileScope internal

description: This resource retrieves information associated with the port-in ID number specified.

get:
    description: Retrieves the information associated with the specified port-in ID number.
    responses:
        200:
            description: The information has been successfully retrieved and displayed in the payload.
            body:
                application/xml:
                    example: |
                        <LnpOrderResponse>
                            <Errors>
                                <Code>7205</Code>
                                <Description>Telephone number is already being processed on another order</Description>
                            </Errors>
                            <ProcessingStatus>CANCELLED</ProcessingStatus>
                            <LoaAuthorizingPerson>The Authguy</LoaAuthorizingPerson>
                            <Subscriber>
                                <SubscriberType>BUSINESS</SubscriberType>
                                <FirstName>First</FirstName>
                                <LastName>Last</LastName>
                                <ServiceAddress>
                                    <HouseNumber>11235</HouseNumber>
                                    <StreetName>Back</StreetName>
                                    <City>Denver</City>
                                    <StateCode>CO</StateCode>
                                    <Zip>27541</Zip>
                                    <County>Canyon</County>
                                    <Country>United States</Country>
                                    <AddressType>Service</AddressType>
                                </ServiceAddress>
                            </Subscriber>
                            <WirelessInfo>
                                <AccountNumber>771297665AABC</AccountNumber>
                                <PinNumber>1234</PinNumber>
                            </WirelessInfo>
                            <TnAttributes>
                                <TnAttribute>Protected</TnAttribute>
                            </TnAttributes>
                            <BillingTelephoneNumber>9195551234</BillingTelephoneNumber>
                            <ListOfPhoneNumbers>
                                <PhoneNumber>9194809871</PhoneNumber>
                            </ListOfPhoneNumbers>
                            <AccountId>20</AccountId>
                            <SiteId>2857</SiteId>
                            <PeerId>317771</PeerId>
                            <LosingCarrierName>Mock Carrier</LosingCarrierName>
                            <VendorName>Bandwidth CLEC</VendorName>
                            <OrderCreateDate>2014-08-04T13:37:06.323Z</OrderCreateDate>
                            <LastModifiedDate>2014-08-04T13:37:08.676Z</LastModifiedDate>
                            <userId>jbm</userId>
                            <LastModifiedBy>jbm</LastModifiedBy>
                            <PartialPort>false</PartialPort>
                            <Immediately>false</Immediately>
                            <BillingType>PORTIN</BillingType>
                        </LnpOrderResponse>

/history: !include history/history.raml
