!fileScope internal
description: |
    This resource is used to manage SIP credentials for subscribers provisioning.

!scope internal
get:
    description: |
        GET is used to retrieve all SIP credentials.
    queryParameters:
            page:
                description: An ID of the first element in a page.  This value will indicate the first value, not the count, of the initial entry in the page being requested.<br>
                    It can be an index of SIP credential or a combination of the user name and domain in form {userName}@{domain}. The initial page is tagged with the ID '1'.
                type: string
                example: 3, user321@bw.com
                default: 1
                required: false
            size:
                description: The number of items to include in a page
                type: integer
                example: 5000
                default: 500
                required: false
            accountId:
                description: The internal account id assigned to the customer SIP credentials are associated with
                type: integer
                example: 5000125
                required: false
            usernamefragment:
                description: The user name fragment. Min length - 3 characters.
                type: string
                example: user32
                required: false
            domainfragment:
                description: The domain fragment. Min length - 3 characters.
                type: string
                example: bw.
                required: false
    responses:
        200:
            description: |
                OK - the SIP credentials retrieval request will return a list of all SIP credentials.
            body:
                application/xml:
                    example: !include sipcredentials_GET_200_response_example.xml

        404:
            description: |
                Not Found - if the account specified does not exist or is locked or there are no SIP credentials for specified search criteria it will result in a not found.
            body:
                application/xml:
                    example: !include sipcredentials_GET_404_response_example.xml

!fileScope internal
/{userName}: !include combination.raml