!fileScope internal
!scope all
description: |
    The E911 product allows E911 capabilities to the account.  The e911 resource is used to establish the Product as active for the identified account.
!scope all
get:
    description: A GET on the E911 product indicates the support (or lack of support) for the E911 capabilities for the specified account.
    responses:
        200:
            description: the 200 response returns with a small payload that indicates that the E911 product is provisioned for the account.
            body:
                application/xml:
                    example: |
                        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                        <AccountProductResponse>
                            <Product>
                                <Name>E911</Name>
                            </Product>
                        </AccountProductResponse>
        404:
            description: |
                NOT FOUND

                is returned if the E911 Resource is not found.  An explanatory payload will be returned with explanation and an error code.
            body:
                application/xml:
                    example: |
                        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                        <AccountProductResponse>
                            <ResponseStatus>
                                <ErrorCode>12017</ErrorCode>
                                <Description>Account '138' does not have product 'E911'</Description>
                            </ResponseStatus>
                        </AccountProductResponse>

put:
    description: |
        a PUT on a E911 resource that already exists will succeed, but does not change the E911 product.
    body:
        application/xml:
            example: |
                <?xml version="1.0"?>
                <Product>
                    <Name>E911</Name>
                </Product>
    responses:
        200:
            description: 200 OK indicates that the E911 capability is associated with the account. If E911 is not already associated with the account then a 404 is returned. NO payload is returned with the 200 OK
        404:
            description: |
                NOT FOUND

                If the E911 Resource is not found a 404 Not Found with an explanatory payload will be returned.
            body:
                application/xml:
                    example: |
                        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                        <AccountProductResponse>
                            <ResponseStatus>
                                <ErrorCode>12017</ErrorCode>
                                <Description>Account '123' does not have product 'E911'</Description>
                            </ResponseStatus>
                        </AccountProductResponse>
/settings: !include settings/e911settings.raml