!fileScope internal
get:
    description: get all get accounts
    responses:
        200:
            description: managed to get all accounts
            body:
                application/json:
                    example: |
                        [
                            {
                                "id":210,
                                "externalAccountId":1,
                                "lcrId":777,
                                "core2Id":1234
                            }
                        ]
post:
    description: create account
    body:
        application/json:
            example: |
                {
                    "id":null,
                    "externalAccountId":1,
                    "lcrId":777,
                    "core2Id":1234
                }
    responses:
        201:
            description: account was successfully created
        400:
            description: required fields are absent or specified externalAccountId is already in use
/{id}:
    get:
        description: get account
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "id":210,
                                "externalAccountId":1,
                                "lcrId":777,
                                "core2Id":1234
                            }
            404:
                description: account with specified id does not exists
    delete:
        description: delete account
        responses:
            200:
                description: account was deleted
            404:
                description: account with specified id was not found
