!fileScope all

description: |
    The resource will query the status of the report that is being generated.
get:
    responses:
        200:
            description: |
                A 200 indicates that the request is valid. The payload indicates the report status: <br>
                <ul>
                    <li><b>PROCESSING</b> - The requested report archive is still being constructed, please check back later.</li>
                    <li><b>COMPLETED</b> - The report archive is constructed.</li>
                </ul>

                For <b>COMPLETED</b> report, fetching the file can be done by issuing a GET request to the resource path in the Location Header.

            headers:
                Location:
                    description: contains the resource of the report file
                    example: https://dashboard.bandwidth.com/api/accounts/9900012/billingreports/a12b456c8-abcd-1a3b-a1b2-0a2b4c6d8e0f2/file
            body:
                application/xml:
                    example: |
                        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                        <BillingReportRetrievalResponse>
                            <ReportStatus>COMPLETED</ReportStatus>
                             <Description>The report archive is constructed.</Description>
                        </BillingReportRetrievalResponse>
        400:
            description: |
                A 400 indicates that the report ID is malformed.
            body:
                application/xml:
                    example: |
                        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                        <BillingReportRetrievalResponse>
                            <ResponseStatus>
                                <ErrorCode>1008</ErrorCode>
                                <Description>'9b428b4c-159b-465f-9667-' is not a valid UUID</Description>
                            </ResponseStatus>
                        </BillingReportRetrievalResponse>
        404:
            description: |
                A 404 indicates that the requested report cannot be found.
            body:
                application/xml:
                    example: |
                        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                        <BillingReportRetrievalResponse>
                            <ResponseStatus>
                                <ErrorCode>15603</ErrorCode>
                                <Description>The requested report was not found.</Description>
                            </ResponseStatus>
                        </BillingReportRetrievalResponse>

/file: !include file/file.raml
