!fileScope internal
!scope all
description: | 
    Enable a separate access network instance to deliver service in conjunction with the CLEC account.
!scope all
get:
    description: A GET on the DedicatedPrivateNetworkTopology product indicates the support (or lack of support) for the DedicatedPrivateNetworkTopology capabilities for the specified account.
    responses: 
        200:
            description: the 200 response returns with a small payload that indicates that the DedicatedPrivateNetworkTopology product is provisioned for the account.
            body: 
                application/xml:
                    example: |
                        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                        <AccountProductResponse>
                            <Product>
                                <Name>DedicatedPrivateNetworkTopology</Name>
                            </Product>
                        </AccountProductResponse>
        404:
            description: |
                NOT FOUND

                is returned if the DedicatedPrivateNetworkTopology Resource is not found.  An explanatory payload will be returned with explanation and an error code.
            body: 
                application/xml:
                    example: |
                        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                        <AccountProductResponse>
                            <ResponseStatus>
                                <ErrorCode>12017</ErrorCode>
                                <Description>Account '138' does not have product 'DedicatedPrivateNetworkTopology'</Description>
                            </ResponseStatus>
                        </AccountProductResponse> 

put:
    description: | 
        a PUT on an DedicatedPrivateNetworkTopology resource that already exists will succeed, but does not change the product assignment.
    body:
        application/xml:
            example: |
                <?xml version="1.0"?>
                <Product>
                    <Name>DedicatedPrivateNetworkTopology</Name>
                </Product>
    responses:
        200:
            description: 200 OK indicates that the DedicatedPrivateNetworkTopology capability is associated with the account. NO payload is returned with the 200 OK. If DedicatedPrivateNetworkTopology is not already associated with the account then a 404 is returned.
/settings: !include settings/dedicatedprivatenetworktopologysettings.raml
