!fileScope external

description: |
    The /availableNumbers API call searches for available phone numbers based on one or more of the following criteria:<br>
    <ul>
        <li>Area Code</li>
        <li>NPA-NXX</li>
        <li>NPA-NXX with Local Area Calling</li>
        <li>NPA-NXX-X</li>
        <li>NPA-NXX-X with Local Area Calling</li>
        <li>RateCenter</li>
        <li>RateCenter with Local Area Calling</li>
        <li>State</li>
        <li>City/State</li>
        <li>Zip Code</li>
        <li>LATA</li>
        <li>Local Vanity</li>
        <li>TollFree Vanity</li>
        <li>TollFree WildCard Pattern</li>
    </ul>
    <br>
    Each choice above has required and optional parameters. Some search parameters can be combined with others.
    Allowed search criteria are limited in case of search by Local Calling Area (see restrictions below).<br>
    <table>
        <tr>
            <th>Search Criteria</th>
            <th>Required Parameters</th>
            <th>Combinable Parameters</th>
            <th>Optional Parameters</th>
        </tr>
        <tr>
            <td>Area Code</td>
            <td>areaCode</td>
            <td>
                rateCenter (state required)<br>
                city (state required)<br>
                state<br>
                lata<br>
                zip
            </td>
            <td>quantity<br>enableTNDetail<br>protected</td>
        </tr>
        <tr>
            <td>NPA-NXX</td>
            <td>npaNxx</td>
            <td>
                rateCenter (state required)<br>
                city (state required)<br>
                state<br>
                lata<br>
                zip<br>
                orderBy
            </td>
            <td>quantity<br>enableTNDetail<br>protected</td>
        </tr>
        <tr>
            <td>NPA-NXX with Local Calling Area</td>
            <td>npaNxx</td>
            <td></td>
            <td>quantity<br>LCA<br>enableTNDetail<br>protected</td>
        </tr>
        <tr>
            <td>NPA-NXX-X</td>
            <td>npaNxxx</td>
            <td>
                rateCenter (state required)<br>
                city (state required)<br>
                state<br>
                lata<br>
                zip<br>
                orderBy
            </td>
            <td>quantity<br>enableTNDetail<br>protected</td>
        </tr>
        <tr>
            <td>NPA-NXX-X with Local Calling Area</td>
            <td>npaNxxx</td>
            <td></td>
            <td>quantity<br>LCA<br>enableTNDetail<br>protected</td>
        </tr>
        <tr>
            <td>RateCenter</td>
            <td>rateCenter<br>state</td>
            <td>
                city<br>
                areaCode/npaNxx/npaNxxx<br>
                lata<br>
                zip<br>
                orderBy
            </td>
            <td>quantity<br>enableTNDetail<br>protected</td>
        </tr>
        <tr>
            <td>RateCenter with Local Calling Area</td>
            <td>rateCenter<br>state</td>
            <td></td>
            <td>quantity<br>LCA<br>enableTNDetail<br>protected</td>
        </tr>
        <tr>
            <td>State</td>
            <td>state</td>
            <td>
                rateCenter<br>
                city<br>
                areaCode/npaNxx/npaNxxx<br>
                lata<br>
                zip
            </td>
            <td>quantity<br>enableTNDetail<br>protected</td>
        </tr>
        <tr>
            <td>City</td>
            <td>city<br>state</td>
            <td>
                rateCenter<br>
                state<br>
                areaCode/npaNxx/npaNxxx<br>
                lata<br>
                zip<br>
                orderBy
            </td>
            <td>quantity<br>enableTNDetail<br>protected</td>
        </tr>
        <tr>
            <td>Zip Code</td>
            <td>zip</td>
            <td>
                rateCenter (state required)<br>
                city (state required)<br>
                state<br>
                areaCode/npaNxx/npaNxxx<br>
                lata<br>
                orderBy
            </td>
            <td>quantity<br>enableTNDetail<br>protected</td>
        </tr>
        <tr>
            <td>LATA</td>
            <td>lata</td>
            <td>
                rateCenter (state required)<br>
                city (state required)<br>
                state<br>
                areaCode/npaNxx/npaNxxx<br>
                zip
            </td>
            <td>quantity<br>enableTNDetail<br>protected</td>
        </tr>
        <tr>
            <td>Local Vanity</td>
            <td>
                areaCode<br>
                localVanity
            </td>
            <td></td>
            <td>
                endsIn<br>
                quantity<br>
                protected<br>
                enableTNdetails
            </td>
        </tr>
        <tr>
            <td>TollFree Vanity</td>
            <td>tollFreeVanity</td>
            <td>orderBy</td>
            <td>quantity</td>
        </tr>
        <tr>
            <td>TollFree WildCard</td>
            <td>tollFreeWildCardPattern</td>
            <td>orderBy</td>
            <td>quantity</td>
        </tr>
    </table>
    <br>
    <table>
        <tr>
            <th>Parameters</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>areaCode</td>
            <td>The allowed number ranges are [2-9] for the first digit and [0-9] for both the second and third digits.</td>
        </tr>
        <tr>
            <td>npaNxx or npaNxxx</td>
            <td>NPA NXX combination to be searched.<br>Valid npa values:[2-9] for the first digit, and [0-9] for both the second and third digits.<br>Valid Nxx values:[2-9] for the first digit, and [0-9] for both the second and third digits.<br>Valid x values [0-9].</td>
        </tr>
        <tr>
            <td>rateCenter</td>
            <td>The abbreviation for the Rate Center</td>
        </tr>
        <tr>
            <td>state</td>
            <td>The two-letter abbreviation of the state the RateCenter is in.</td>
        </tr>
        <tr>
            <td>city</td>
            <td>The name of the city.</td>
        </tr>
        <tr>
            <td>zip</td>
            <td>A five-digit (XXXXX) or nine-digit (XXXXX-XXXX) zip-code value.</td>
        </tr>
        <tr>
            <td>lata</td>
            <td>A maximum five digit (XXXXX) numeric format.</td>
        </tr>
        <tr>
            <td>localVanity</td>
            <td>Requested vanity number. Valid range is from 4 to 7 alphanumeric characters</td>
        </tr>
        <tr>
            <td>tollFreeVanity</td>
            <td>The Toll Free requested vanity number. Valid range is from 4 to 7 alphanumeric characters</td>
        </tr>
        <tr>
            <td>tollFreeWildCardPattern</td>
            <td>The requested Toll Free 3 digit wild card pattern. Examples: 8**, 80*, 87*, etc.</td>
        </tr>
        <tr>
            <td>quantity</td>
            <td>The desired quantity of requested numbers. Values range from 1-5000. If no quantity is specified, the default of 5000 is returned.</td>
        </tr>
        <tr>
            <td>enableTNDetail</td>
            <td>If set to true, a list of details associated with the telephone number (rate center abbreviation, rate center host city, state, and LATA) will be displayed along with the telephone number. This value is set to false by default.</td>
        </tr>
        <tr>
            <td>LCA</td>
            <td>Local Calling Area. If this parameter is specified then Telephone Numbers that are likely in the Local Calling Area of  the stated Rate Center, NPANXX or NPANNXX will be returned, in addition to those that *exactly* match the query will be returned.  Since LCA logic is not always symmetric and not always inclusive of RC and NPANXX search criteria, this result reflects somewhat of an approximation.  The parameter value is true or false. The default is true</td>
        </tr>
        <tr>
            <td>endsIn</td>
            <td>Intended to use with <i>localVanity</i> only. The parameter value is true or false. If set to true, the search will look for only numbers which end in specified <i>localVanity</i>, otherwise <i>localVanity</i> sequence can be met anywhere in last 7 number digits. The default is false.</td>
        </tr>
        <tr>
            <td>orderBy</td>
            <td>The field by which the returned numbers will be sorted. Only supported if at least one of the following search criteria is specified: npaNxx or npaNxxx, rateCenter, city, zip, tollFreeVanity, tollFreeWildCardPattern. Allowed values are <i>fullNumber</i>, <i>npaNxxx</i>, <i>npaNxx</i>,  and <i>areaCode></td>
        </tr>
        <tr>
            <td>protected</td>
            <td>
            A query parameter, that governs, how the Protected status of numbers impacts the search results<br>
            The overall behavior of the protected search values are described in the table below:<br>
            <table>
                <tr>
                    <th>Query Parameter</th>
                    <th>Description</th>
                </tr>
                <tr>
                    <td>NONE</td>
                    <td>The numbers returned in the payload will not contain any numbers that are tagged as Protected</td>
                </tr>
                <tr>
                    <td>ONLY</td>
                    <td>The numbers returned in the payload will all be tagged as Protected. No "unProtected" numbers will be returned</td>
                </tr>
                <tr>
                    <td>MIXED</td>
                    <td>The protected status of the numbers will be ignored in the search - all types of numbers will be returned</td>
                </tr>
            </table>
            </td>
        </tr>
    </table>

get:
    description: Retrieves the phone numbers according to the input parameters
    queryParameters:
        quantity:
            type: integer
            description: The desired quantity of requested numbers. Values range from 1-5000.
            default: 5000
            example: 30
        enableTNDetail:
            type: boolean
            description: If set to true, a list of details associated with the telephone number (rate center, abbreviation, city, state, and LATA) will be displayed along with the TN.
            default: false
        LCA:
            type: boolean
            description: Values are true or false.
            default: true
        endsIn:
            type: boolean
            description: Intended to use with <i>localVanity</i> only. If set to true, the search will look for only numbers which end in specified <i>localVanity</i>, otherwise <i>localVanity</i> sequence can be met anywhere in last 7 number digits. The default is false.
            default: false
        areaCode:
            type: integer
            description: The 3-digit area code associated with the TN. Allowed number ranges are [2-9] for the first digit and [0-9] for both the second and third digits.
            example: 435
        npaNxx:
            type: integer
            description: |
                The 6 prefix associated with the TN.<br>
                Allowed number ranges for NPA are [2-9] for the first digit and [0-9] for both the second and third digits.<br>
                Allowed number ranges for NXX are [2-9] for the first digit and [0-9] for both the second and third digits.<br>
        npaNxxx:
            type: integer
            description: |
                The 7-digit prefix associated with the TN.<br>
                Allowed number ranges for NPA are [2-9] for the first digit and [0-9] for both the second and third digits.<br>
                Allowed number ranges for NXXX are [2-9] for the first digit and [0-9] the rest of the (X) digits.<br>
        lata:
            type: integer
            description: A maximum five digit (XXXXX) numeric format
            example: 244
        rateCenter:
            type: string
            description: The abbreviation for the rateCenter
            example: Cary
        city:
            type: string
            description: The name of the city.
            example: RALEIGH
        state:
            type: string
            description: The two-letter abbreviation of the state the RateCenter is in
            example: NC
        tollFreeVanity:
            type: string
            description: The Toll Free requested vanity number. Valid range is 7+ digits alphanumeric.
            example: NEWCARS
        tollFreeWildCardPattern:
            type: string
            description: The Toll Free requested wild card pattern. valid range is 3 digits.
            example: 8**, 80*, 87*
        localVanity:
            type: string
            description: Requested vanity number. Valid range is from 4 to 7 alphanumeric characters.
            example: NEWCARS
        zip:
            type: integer
            description: A five-digit (XXXXX) or nine-digit (XXXXX-XXXX) format value.
            example: 27607
        orderBy:
            type: string
            enum: [fullNumber, npaNxxx, npaNxx,areaCode]
            description: The field by which the results should be sorted
    responses:
        200:
            description: A list of available numbers is provided.  Additional information is available if the queryParameter enableTNDetail is true.
            body:
                application/xml:
                    example: |
                        <SearchResult>
                            <ResultCount>384</ResultCount>
                            <TelephoneNumberList>
                                <TelephoneNumber>4354776112</TelephoneNumber>
                                            <!---- SNIP ---->
                                <TelephoneNumber>4357095160</TelephoneNumber>
                            </TelephoneNumberList>
                        </SearchResult>
        400:
            description: Invalid/missing input parameter
            body:
                application/xml:
                    example: |
                        <SearchResult>
                            <Error>
                                <Code>4010</Code>
                                <Description>One of more required search parameters are null or empty, please refer to the api documentation</Description>
                            </Error>
                        </SearchResult>
