!fileScope all
description: |
    This resource is used to manage single SIP credential for subscribers provisioning.<br>

!scope all
get:
    description: |
        GET is used to retrieve SIP credential for the account by unique combination of user name and domain.

    responses:
        200:
            description: |
                OK - will return full information about SIP credential on this account for specified user name and domain.
            body:
                application/xml:
                    example: !include sipcredential_GET_200_response_example.xml

        404:
            description: |
                Not Found - if the account specified does not exist or is locked or there are no SIP credential that corresponds to specified combination of user name and domain it will result in a not found.
            body:
                application/xml:
                    example: !include sipcredential_GET_404_response_example.xml


!scope all
put:
    description: |
        PUT is used to change single SIP credential.<br>
        It is not possible to change the UserName or the Domain associated with the Hash Values.  To do so requires deletion of one set of credentials and addition of a new set of credentials.<br>

        The key data elements in the submission are -
         <table style="text-align: left; width: 80%;"
         border="1" cellpadding="2" cellspacing="2">
          <tbody>
            <tr>
              <td>Hash1</td>
              <td>This is hash value #1 in MD5 representation. Field is required. Max length - 64 characters.</td>
            </tr>
            <tr>
              <td>Hash1b</td>
              <td>This is hash value #2 in MD5 representation. Field is optional. Max length - 64 characters.</td>
            </tr>
          </tbody>
        </table>

    body:
        application/xml:
            example: |
                <SipCredential>
                    <Hash1>1g32gadgs433dd4</Hash1>
                    <Hash1b>1g32gadgs433d24</Hash1b>
                </SipCredential>
    responses:
        200:
            description: |
                OK - the SIP credential was successfully updated.
            body:
                application/xml:
                    example: !include sipcredential_PUT_200_response_example.xml

        400:
            description: |
                Bad Request - the SIP credential was not updated.
            body:
                application/xml:
                    example: !include sipcredential_PUT_400_response_example.xml

        404:
            description: |
                Not Found - the SIP credential was not found on the account for specified combination of user name and domain.
            body:
                application/xml:
                    example: !include sipcredential_PUT_404_response_example.xml

!scope all
delete:
    description: |
        DELETE is used to delete SIP credential.

    responses:
        200:
            description: |
                OK - the SIP credential was deleted successfully.

        404:
            description: |
                Not Found - the SIP credential was not found on the account for specified combination of user name and domain.
            body:
                application/xml:
                    example: !include sipcredential_DELETE_404_response_example.xml
!fileScope all