!fileScope internal

description: This is a stub for the mockpot portouts resource path.  This needs documenting by somebody that knows how the mockpot works

get:
    responses: 
        405:
            description: Method Not Allowed - Who knows what it really means ???
post:
    description: This is the only method that really does anything - but I don't understand the payload, and don't know the purpose.  
    responses: 
        400:
            description: In this case I submitted a null payload - I suspect that the correct payload would create the desired result
put:
    responses:    
        405:
            description: Method Not Allowed - Who knows what it really means ???