!fileScope all
# note that this file is shared between 5 order types - 
#  - orders
#  - disconnects
#  - portins
#  - portouts
#  - inporttoaccount
#  - lidbs
#  - dldas
# 
description: |
    The /notes resource manages a note or set of notes associated with an order.  Notes can only be appended to the collection, and are not individually addressable or modifiable once added.
!scope all
post:
    description: Updates the Notes resource by adding a note.
    body:
        application/xml:
            example:
                <?xml version="1.0" encoding="UTF-8"?>
                <Note>
                   <UserId>user id</UserId>
                   <Description>note text</Description>
                   !scope internal <Internal>false</Internal>   <!-- note created by admin is implicitly internal unless this tag with "false" value is specified -->
                </Note>
    responses:
        201:
            description: CREATED - the note has been created and added to the collection of notes associated with the order.  A link to the note is included in the Location header of the response.  No body is returned
        400:
            description: Bad Request - the note has not been created because the payload is incomplete or in error.  An error payload is provided in the repsonse.
            body:
                application/xml:
                    example: |
                        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                        <NoteResponse>
                            <ResponseStatus>
                                <ErrorCode>12501</ErrorCode>
                                <Description>Username is required</Description>
                            </ResponseStatus>
                        </NoteResponse>           
!scope all
get:
    description: Retrieve the set of notes associated with an order.
    responses:
        200:
            description: OK - there are Notes associated with the order, and they have been returned in the response.
            body:
                application/xml:
                    example: |
                        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                        <Notes>
                            <Note>
                                <Id>87037</Id>
                                <UserId>jbm</UserId>
                                <Description>This is a test note</Description>
                                <LastDateModifier>2014-11-16T04:01:10.000Z</LastDateModifier>
                                !scope internal
                                <Internal>false</Internal>    <!-- admin only -->
                            </Note>
                            <Note>
                                <Id>87039</Id>
                                <UserId>smckinnon</UserId>
                                <Description>This is a second test note</Description>
                                <LastDateModifier>2014-11-16T04:08:46.000Z</LastDateModifier>
                                !scope internal
                                <Internal>false</Internal>    <!-- admin only -->
                            </Note>
                        </Notes>                    
        204:
            description: No Content - there are no Notes associated with the order.  Since the notes resource is an aggregate rather than addressed resource the generic no content response is used, rather than a 404 as would be used if the resource was addressed with an identifier
