description: API for work with TermServices

/carrier: !include carrier.raml
/account: !include account.raml
/attributes: !include attributeMetadata.raml
/product: !include product.raml
/routingexception: !include routingException.raml
/carriermask: !include carrierMask.raml
/ratedeckassignment: !include ratedeckassignment.raml
/ratedeck: !include rateDeck.raml