!fileScope external

description: Retrieves the area codes of the phone numbers from the specified order.

!scope external
get:
    description: Retrieves the area codes of the phone numbers from the specified order.
    responses:
        200:
            body:
                application/xml:
                    example: |
                        <TelephoneDetailsReports>
                            <TelephoneDetailsReport>
                                <AreaCode>888</AreaCode>
                                <Count>1</Count>
                            </TelephoneDetailsReport>
                        </TelephoneDetailsReports>
