!fileScope all

description: |
    It is often useful to attach additional data to an order in the form of an attached file, and so the existing LOA capability has been extended to optionally allow different file information to be included with a file, to describe type and purpose information.  The MetaData associated with a file includes a file document name and a document type, which is one of [LOA | INVOICE | CSR | OTHER].<br>

    Naming of the existing "loas" API has been preserved to ensure backwards compatibility.

!scope all
get:
    description: Retrieves the metadata associated with the file.

    responses:
        200:
            description: |
                The Metatdata has been successfully retrieved.
            body:
                application/xml:
                    example: |
                        <FileMetaData>
                           <DocumentName> [string] </DocumentName>
                           <DocumentType> [LOA | INVOICE | CSR | OTHER] </DocumentType>
                        </FileMetaData>

        404:
            description: |
                a 404 indicates that the indicated file was not found in conjunction with the portin id.

!scope all
put:
    description: |
        Associate metadata with the file named in the resource path.  This will describe the file, and declare the data that is contained in the file, selected from a list of [LOA | INVOICE | CSR | OTHER].
    body:
        application/xml:
            example: |
                <FileMetaData>
                   <DocumentName> [string] </DocumentName>
                   <DocumentType> [LOA | INVOICE | CSR | OTHER] </DocumentType>
                </FileMetaData>

    responses:
        200:
            description: Successful update of the metadata associated with the identified file.
        400:
            description: Some error has occured as a result of the attempt.

delete:
    description: Deletes the metadata previously associated with the identified file.

    responses:
        200:
            description: |
                The 200 OK  indicates a successful deletion of the identified metadata.

        404:
            description: |
                a 404 indicates that the indicated file was not found in conjunction with the portin id.
