!fileScope internal
get:
  description: get all attributes for account
  responses:
    200:
      body:
        application/xml:
          example:
            <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
            <TerminationAttributesResponse>
                <TerminationAttributesWrapper>
                    <accountId>42</accountId>
                    <TerminationAttributes>
                        <TerminationAttribute>
                            <id>2</id>
                            <type>TRACE</type>
                            <value>true</value>
                            <effectiveDate>2014-10-23T12:49:18</effectiveDate>
                            <inEffectiveDate>2014-10-23T12:49:18</inEffectiveDate>
                            <externalId>5</externalId>
                        </TerminationAttribute>
                    </TerminationAttributes>
                </TerminationAttributesWrapper>
            </TerminationAttributesResponse>
post:
    description: add to customer attribute
    body:
      application/xml:
          example:
              <TerminationAttribute>
                <type>TRACE</type>
                <value>true</value>
                <effectiveDate>2014-10-23T12:59:30</effectiveDate>
                <inEffectiveDate>2014-10-23T12:59:30</inEffectiveDate>
              </TerminationAttribute>
    responses:
        201:
            description: attribute was successfully added
        404:
            description: specified in request account was not found
/{attributeId}:
    get:
        description: get account attribute by id
        responses:
          200:
            body:
              application/xml:
                example:
                  <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                  <TerminationAttributeResponse>
                    <TerminationAttributeWrapper>
                        <accountId>44</accountId>
                        <TerminationAttribute>
                            <id>4</id>
                            <type>TRACE</type>
                            <value>true</value>
                            <effectiveDate>2014-10-23T13:10:18</effectiveDate>
                            <inEffectiveDate>2014-10-23T13:10:18</inEffectiveDate>
                            <externalId>7</externalId>
                        </TerminationAttribute>
                    </TerminationAttributeWrapper>
                  </TerminationAttributeResponse>
          404:
            description: account or attribute was not found

    put:
        description: update account attribute (attribute value)
        body:
          application/xml:
              example:
                  <TerminationAttribute>
                    <type>TRACE</type>
                    <value>false</value>
                    <effectiveDate>2014-10-23T12:59:30</effectiveDate>
                    <inEffectiveDate>2014-10-23T12:59:30</inEffectiveDate>
                  </TerminationAttribute>
        responses:
            200:
                body:
                    application/xml:
                        example: |
                            <TerminationAttributeResponse>
                                <TerminationAttributeWrapper>
                                    <accountId>45</accountId>
                                    <TerminationAttribute>
                                        <id>5</id>
                                        <type>TRACE</type>
                                        <value>false</value>
                                        <effectiveDate>2014-10-23T13:20:29</effectiveDate>
                                        <inEffectiveDate>2014-10-23T13:20:29</inEffectiveDate>
                                        <externalId>8</externalId>
                                    </TerminationAttribute>
                                </TerminationAttributeWrapper>
                            </TerminationAttributeResponse>
            400:
                description: update validation failed, eg changed forbidden fields (like metadata name)
            404:
                description: account or attribute was not found
    delete:
        description: delete account attribute
        responses:
            200:
                description: account attribute was deleted
            400:
                description: some required value was not found
            404:
                description: account or attribute was not found