!fileScope all
!scope external
description: Allows the manipulation of a user's password.
!scope external
put:
    
    description: Update a user's password.   Security is maintained by requiring the user's existing password as part of the authentication for the API call.
    body:
        application/xml:
            example: |
                <Password>$uper$ecure</Password> <!-- required, min length: 6, max length: 20 -->
    responses:
        200:
            body: 
                application/xml:
                    example: empty response
        400:
            body:
                application/xml:
                    example: |
                        <UserResponse>
                            <ResponseStatus>
                            <ErrorCode>12504</ErrorCode>
                            <Description>Password must be at least 6 characters long</Description>
                            </ResponseStatus>
                        </UserResponse>