!fileScope internal

get:
  description: |
        Retrieve more detailed information about a specific product (including associated attributes).

  responses:
    200:
      description: |
              Information about product:
                <ul>
                <li> ProfileID (long) - a product may be associated with a profile. (profile in this case can't have any contained products)</li>
                <li> ProductId (long) - product identifier. </li>
                <li> ProductName (string) - product name. </li>
                <li> ProductDescription (string) - product description </li>
                  <ul>
                    <i>ProductAttributeList</i>
                    <li>Attribute (string) - name of the attribute</li>
                    <li>AttributeValue - an attribute value </li>
                  </ul>
                </ul>
      body:
         application/xml:
            example: !include product.xml

    404:
            description: Not Found.  If any errors are found in the processing of the query string a 404 will be returned.  Note that parameters that are not recognized are not considered errors, and are just ignored.

